"""accounts add column age

Revision ID: 098ec3c04317
Revises: cd43a24a1e2b
Create Date: 2025-02-10 19:53:34.325901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098ec3c04317'
down_revision: Union[str, None] = 'cd43a24a1e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('age', sa.Integer(), server_default='20', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'age')
    # ### end Alembic commands ###
