"""row_changes

Revision ID: b008c491ed74
Revises: 533722d1fb95
Create Date: 2025-03-22 14:08:04.687171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b008c491ed74'
down_revision: Union[str, None] = '533722d1fb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('row_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_row_id', 'row_changes', ['row_id'], unique=False)
    op.create_index('idx_table_name', 'row_changes', ['table_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_table_name', table_name='row_changes')
    op.drop_index('idx_row_id', table_name='row_changes')
    op.drop_table('row_changes')
    # ### end Alembic commands ###
