# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mq.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08mq.proto\"\x14\n\x05Login\x12\x0b\n\x03uid\x18\x01 \x01(\x03\"\x15\n\x06Logout\x12\x0b\n\x03uid\x18\x01 \x01(\x03\"\x14\n\x05\x41larm\x12\x0b\n\x03tip\x18\x01 \x01(\t\">\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\t\x12\x0e\n\x06kwargs\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mq_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGIN._serialized_start=12
  _LOGIN._serialized_end=32
  _LOGOUT._serialized_start=34
  _LOGOUT._serialized_end=55
  _ALARM._serialized_start=57
  _ALARM._serialized_end=77
  _TASK._serialized_start=79
  _TASK._serialized_end=141
# @@protoc_insertion_point(module_scope)
